apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: alpine:latest
      script: |
        #!/bin/sh
        echo "Cleaning up workspace..."
        rm -rf /workspace/source/tmp
        echo "Cleanup complete!"
# --------- Task 4 (Cleanup Task) ---------

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test-task
spec:
  steps:
    - name: run-tests
      image: python:3.10
      script: |
        #!/bin/sh
        pip install pytest
        pytest
# --------- Task 5 (Nose Test Task) ---------
